/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serviatech_hwapi_CanAPI */

#ifndef _Included_com_serviatech_hwapi_CanAPI
#define _Included_com_serviatech_hwapi_CanAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serviatech_hwapi_CanAPI
 * Method:    opencan
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_serviatech_hwapi_CanAPI_opencan
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_serviatech_hwapi_CanAPI
 * Method:    closecan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_serviatech_hwapi_CanAPI_closecan
  (JNIEnv *, jobject);

/*
 * Class:     com_serviatech_hwapi_CanAPI
 * Method:    writecan
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_serviatech_hwapi_CanAPI_writecan
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_serviatech_hwapi_CanAPI
 * Method:    readcan
 * Signature: ()Lcom/serviatech/hwapi/CanFrame;
 */
JNIEXPORT jobject JNICALL Java_com_serviatech_hwapi_CanAPI_readcan
  (JNIEnv *, jobject);

/*
 * Class:     com_serviatech_hwapi_CanAPI
 * Method:    setFilter
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_serviatech_hwapi_CanAPI_setFilter
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
