/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serviatech_hwapi_GPIO */

#ifndef _Included_com_serviatech_hwapi_GPIO
#define _Included_com_serviatech_hwapi_GPIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serviatech_hwapi_GPIO
 * Method:    write
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_serviatech_hwapi_GPIO_write
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_serviatech_hwapi_GPIO
 * Method:    read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_serviatech_hwapi_GPIO_read
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
